### ISSUE TITLE
Emoji, GIF's and Stickers

### ISSUE THREAD

**Issue by AbhianvGupta** [amirisback/frogo-keyboard-open-source#1]
Thanks for making this awesome code and I took help from your code but
I want to add emoji, GIF's and Sticker section in this keyboard.
Please guide me here how to add them
Any Suggestions?

**Comment by amirisback** [comment]
thanks for your report, i will try update as soon as possible

**Comment by AbhianvGupta** [comment]
> thanks for your report, i will try update as soon as possible

yes please
I am learning this and I need it urgently 
If possible please make it asap

**Comment by amirisback** [comment]
For now I can only add emojis

**Comment by amirisback** [comment]
Please Help Give Star Thank You

**Comment by amirisback** [comment]
you can check file change here https://github.com/amirisback/frogo-keyboard-open-source/pull/2
